services:
  - type: web
    name: smart-rule-based-approval-engine-backend
    runtime: go
    plan: free
    buildCommand: go build -o app ./cmd/server
    startCommand: ./app
    envVars:
      - key: APP_NAME
        value: approval-engine-prod
      - key: APP_PORT
        value: "8080"
      - key: DB_HOST
        value: db.kawfacdktsfcjbdnsqdt.supabase.co
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: postgres
      - key: DB_PASSWORD
        value: Supabase@123
      - key: DB_NAME
        value: postgres
      - key: DB_SSLMODE
        value: require
      - key: JWT_SECRET
        value: 6b387057bb171ea2887de04cfcd251b23af1c8edd14ede14eefa527b860c5e19
      - key: CORS_ORIGINS
        value: https://smart-rule-based-approval-engine.vercel.app/,http://localhost:5173
